import {useEffect,useMemo,useState} from 'react'
import {BookOpen,CalendarDays,Check,Circle,FileText,Mic,MicOff,NotebookPen,Plus,Target,Trash2} from 'lucide-react'
import {useAuth} from '../context/AuthContext'
import {commerceSubjects} from '../data/commerceSyllabus'
const API='/api/v1',today=()=>new Date().toISOString().slice(0,10)
export default function MyLearningPage(){
 const{user}=useAuth();const[resources,setResources]=useState([]),[plans,setPlans]=useState([]),[checks,setChecks]=useState([]),[entries,setEntries]=useState([]),[tab,setTab]=useState('today'),[cadence,setCadence]=useState('daily'),[subject,setSubject]=useState('Business Studies'),[topic,setTopic]=useState(''),[startDate,setStartDate]=useState(today()),[endDate,setEndDate]=useState(today()),[weekday,setWeekday]=useState(new Date().getDay()),[diaryTitle,setDiaryTitle]=useState('My day'),[diaryText,setDiaryText]=useState(''),[listening,setListening]=useState(false),[busy,setBusy]=useState(false)
 const headers=async()=>({Authorization:`Bearer ${await user.getIdToken()}`,'Content-Type':'application/json'})
 const load=async()=>{if(!user)return;const h=await headers();const[a,b,c]=await Promise.all([fetch(`${API}/learning/history`,{headers:h}),fetch(`${API}/learning/plans`,{headers:h}),fetch(`${API}/learning/diary`,{headers:h})]);if(a.ok)setResources((await a.json()).resources||[]);if(b.ok){const d=await b.json();setPlans(d.plans||[]);setChecks(d.checks||[])}if(c.ok)setEntries((await c.json()).entries||[])}
 useEffect(()=>{load()},[user])
 const subjects=useMemo(()=>resources.reduce((m,x)=>{(m[x.subject]??=[]).push(x);return m},{}),[resources])
 const occurs=(p,date)=>{if(date<p.start_date||date>p.end_date)return false;const d=new Date(`${date}T12:00:00`);if(p.cadence==='daily')return true;if(p.cadence==='weekly')return d.getDay()===Number(p.weekday);return d.getDate()===new Date(`${p.start_date}T12:00:00`).getDate()}
 const done=(id,date=today())=>checks.some(c=>c.plan_id===id&&c.occurrence_date===date),todayPlans=plans.filter(p=>occurs(p,today()))
 const addPlan=async e=>{e.preventDefault();if(!topic.trim())return;setBusy(true);await fetch(`${API}/learning/plans`,{method:'POST',headers:await headers(),body:JSON.stringify({title:topic,topic,subject,cadence,startDate,endDate,weekday:Number(weekday)})});setTopic('');setBusy(false);load()}
 const toggle=async(id,date=today())=>{await fetch(`${API}/learning/plans/${id}/check`,{method:'POST',headers:await headers(),body:JSON.stringify({date})});load()}
 const remove=async(type,id)=>{if(!window.confirm('Delete this saved item permanently?'))return;const r=await fetch(`${API}/learning/${type}/${id}`,{method:'DELETE',headers:await headers()});if(r.ok)load()}
 const saveDiary=async()=>{if(!diaryText.trim())return;setBusy(true);await fetch(`${API}/learning/diary`,{method:'POST',headers:await headers(),body:JSON.stringify({entryDate:today(),title:diaryTitle,content:diaryText})});setDiaryText('');setBusy(false);load()}
 const voice=()=>{const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){alert('Voice typing is not supported in this browser. Try Chrome or Edge.');return}const r=new Speech();r.lang='en-IN';r.interimResults=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onresult=e=>setDiaryText(v=>`${v}${v?' ':''}${e.results[0][0].transcript}`);r.start()}
 const PlanCard=({p,date=today()})=><div className={`plan-card ${done(p.id,date)?'done':''}`}><button onClick={()=>toggle(p.id,date)}>{done(p.id,date)?<Check/>:<Circle/>}<div><span>{p.cadence} · {p.subject}</span><strong>{p.title}</strong><small>{p.start_date} → {p.end_date}</small></div></button><button className="item-delete" onClick={()=>remove('plans',p.id)} aria-label="Delete target"><Trash2/></button></div>
 const ResourceBody=({item})=>{const data=item.content||{};if(item.resource_type==='roadmap')return <div className="saved-roadmap"><header><div><span>STUDY ROADMAP</span><h3>{data.title||item.title}</h3><p>{data.strategy}</p></div><div><b>{data.duration_weeks||data.milestones?.length||0}</b><small>WEEKS</small></div></header><div className="saved-roadmap-weeks">{data.milestones?.map((week,index)=><article key={week.week||index}><div className="saved-week-head"><i>{String(week.week||index+1).padStart(2,'0')}</i><div><span>WEEK {week.week||index+1} · {week.estimated_hours||data.weekly_hours||0} HOURS</span><h4>{week.title}</h4></div></div><div className="saved-week-grid"><section><b>Topics</b>{week.topics?.map((x,i)=><p key={i}>• {x}</p>)}</section><section><b>Tasks</b>{week.tasks?.map((x,i)=><p key={i}>• {x}</p>)}</section>{week.daily_plan?.length>0&&<section><b>Day-wise plan</b>{week.daily_plan.map((x,i)=><p key={i}>{x}</p>)}</section>}{week.checkpoint&&<section className="saved-checkpoint"><b>Checkpoint</b><p>{week.checkpoint}</p></section>}</div></article>)}</div></div>;if(data.paper)return <pre>{data.paper}</pre>;if(data.content)return <div className="saved-text">{String(data.content).split('\n').map((x,i)=><p key={i}>{x||' '}</p>)}</div>;return <pre>{JSON.stringify(data,null,2)}</pre>}
 return <div className="learning-hub min-h-screen pt-24 pb-20 px-4"><div className="max-w-7xl mx-auto"><header><span>MY LEARNING SPACE</span><h1>Plan clearly.<br/><em>Learn consistently.</em></h1><p>Your subject-wise library, today's priorities and private study diary—all connected to your account.</p></header><div className="learning-stats"><article><FileText/><div><strong>{resources.length}</strong><span>Saved resources</span></div></article><article><Target/><div><strong>{todayPlans.filter(x=>!done(x.id)).length}</strong><span>Left today</span></div></article><article><Check/><div><strong>{todayPlans.filter(x=>done(x.id)).length}</strong><span>Done today</span></div></article></div><div className="learning-tabs"><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}><Target/>Today</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><BookOpen/>Library</button><button className={tab==='planner'?'active':''} onClick={()=>setTab('planner')}><CalendarDays/>Planner</button><button className={tab==='diary'?'active':''} onClick={()=>setTab('diary')}><NotebookPen/>My Diary</button></div>
 {tab==='today'&&<section className="today-board"><div><span>{new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</span><h2>Today's focus</h2><p>Only the targets scheduled for today appear here.</p></div><div className="target-list">{todayPlans.length?todayPlans.map(p=><PlanCard key={p.id} p={p}/>):<div className="learning-empty"><Target/><h2>Nothing planned today</h2><p>Add a daily, weekly or monthly target from Planner.</p></div>}</div></section>}
 {tab==='history'&&<section className="subject-library">{!resources.length?<div className="learning-empty"><BookOpen/><h2>No saved resources yet</h2><p>Generated summaries, flashcards, quizzes, roadmaps and papers will be organised here by subject.</p></div>:Object.entries(subjects).map(([name,items])=><article className="subject-shelf" key={name}><header><span>{name.slice(0,2).toUpperCase()}</span><div><h2>{name}</h2><small>{items.length} saved item{items.length===1?'':'s'}</small></div></header><div>{items.map(item=><div className="saved-resource-row" key={item.id}><details><summary><b>{item.resource_type.replace('-',' ')}</b><strong>{item.title}</strong><small>{new Date(item.created_at).toLocaleDateString()}</small></summary><p>{item.chapters}</p><ResourceBody item={item}/></details><button className="item-delete" onClick={()=>remove('resources',item.id)} aria-label="Delete saved resource"><Trash2/></button></div>)}</div></article>)}</section>}
 {tab==='planner'&&<section className="planner-pro"><form onSubmit={addPlan}><span>CREATE A PLAN</span><h2>Set a recurring target</h2><div className="cadence-switch">{['daily','weekly','monthly'].map(x=><button type="button" className={cadence===x?'active':''} onClick={()=>setCadence(x)} key={x}>{x}</button>)}</div><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{commerceSubjects.map(s=><option key={s.id}>{s.name}</option>)}</select></label><label>Target<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. Learn one Business Studies chapter"/></label><div className="date-pair"><label>From<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>Until<input type="date" min={startDate} value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div>{cadence==='weekly'&&<label>Repeat on<select value={weekday} onChange={e=>setWeekday(e.target.value)}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((x,i)=><option value={i} key={x}>{x}</option>)}</select></label>}{cadence==='monthly'&&<div className="plan-note">Repeats monthly on day {new Date(`${startDate}T12:00:00`).getDate()} within the selected range.</div>}<button disabled={busy||!topic.trim()}><Plus/>Save {cadence} target</button></form><div className="plan-columns">{['daily','weekly','monthly'].map(type=><article key={type}><h3>{type} targets</h3><div className="target-list">{plans.filter(p=>p.cadence===type).map(p=><PlanCard key={p.id} p={p}/>)}</div></article>)}</div></section>}
 {tab==='diary'&&<section className="diary-layout"><div className="diary-editor"><span>TODAY · {today()}</span><input value={diaryTitle} onChange={e=>setDiaryTitle(e.target.value)} placeholder="Entry title"/><textarea value={diaryText} onChange={e=>setDiaryText(e.target.value)} placeholder="Write what you studied, understood, found difficult, or want to remember…"/><div><button className={listening?'recording':''} onClick={voice}>{listening?<MicOff/>:<Mic/>}{listening?'Listening…':'Voice to text'}</button><button disabled={busy||!diaryText.trim()} onClick={saveDiary}>Save entry</button></div></div><div className="diary-entries"><h2>Previous entries</h2>{entries.map(e=><article key={e.id}><button className="item-delete" onClick={()=>remove('diary',e.id)} aria-label="Delete diary entry"><Trash2/></button><span>{new Date(`${e.entry_date}T12:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'long',year:'numeric'})}</span><h3>{e.title}</h3><p>{e.content}</p></article>)}</div></section>}
 </div></div>
}
